# se-z 0.1A managed paths
d /run/se-z 0711 root root -
d /var/lib/se-z 0750 root root -
d /var/lib/se-z-gateway 0750 se-z-gateway se-z-gateway -
d /var/lib/se-z-recovery 0700 root root -
d /etc/se-z 0711 root root -
d /etc/se-z/keys 0750 root se-z-gateway -
d /opt/se-z 0755 root root -
d /opt/se-z/releases 0755 root root -
