import {createHash,createHmac,randomBytes,randomUUID} from 'node:crypto';
import {chmodSync,closeSync,existsSync,fsyncSync,mkdirSync,openSync,readFileSync,readlinkSync,renameSync,symlinkSync,unlinkSync,writeFileSync} from 'node:fs';
import {dirname,join,resolve} from 'node:path';
import {PHASE3} from './constants.mjs';
export const EMPTY_SLOT=()=>({schemaVersion:PHASE3.stateSchema,sequence:0,releaseIdentity:null,clients:{},authorizationRequests:{},githubLogins:{},authorizationCodes:{},refreshFamilies:{},revocations:{tokenIds:{},families:{},clients:{}},replayEvents:[],tokenIds:{},migration:null});
export const sha256=value=>createHash('sha256').update(value).digest('hex');
export const tokenHash=(secret,token)=>createHmac('sha256',secret).update(token).digest('hex');
export const randomToken=(bytes=32)=>randomBytes(bytes).toString('base64url');
function fsyncPath(path){const fd=openSync(path,'r');try{fsyncSync(fd);}finally{closeSync(fd);}}
export function atomicWriteJson(path,value){mkdirSync(dirname(path),{recursive:true,mode:0o700});const temp=`${path}.${process.pid}.${randomUUID()}.tmp`;try{writeFileSync(temp,`${JSON.stringify(value,null,2)}\n`,{mode:0o600,flag:'wx'});chmodSync(temp,0o600);fsyncPath(temp);renameSync(temp,path);fsyncPath(dirname(path));}finally{if(existsSync(temp))unlinkSync(temp);}}
export class GatewayState{
 constructor(root,options={}){this.root=resolve(root);this.hashSecret=options.hashSecret??randomBytes(32);this.now=options.now??(()=>Date.now());this.ensureLayout();}
 slotPath(slot){if(!['blue','green'].includes(slot))throw new Error('invalid slot');return join(this.root,'slots',slot);} dbPath(slot){return join(this.slotPath(slot),'state.json');}
 ensureLayout(){for(const p of [this.root,join(this.root,'slots'),this.slotPath('blue'),this.slotPath('green'),join(this.root,'locks'),join(this.root,'snapshots'),join(this.root,'metadata')])mkdirSync(p,{recursive:true,mode:0o700});for(const slot of ['blue','green'])if(!existsSync(this.dbPath(slot)))atomicWriteJson(this.dbPath(slot),EMPTY_SLOT());if(!existsSync(join(this.root,'active')))symlinkSync('slots/blue',join(this.root,'active'));}
 activeSlot(){const target=readlinkSync(join(this.root,'active'));const slot=target.split('/').at(-1);if(!['blue','green'].includes(slot))throw new Error('gateway_state_corrupt');return slot;}
 read(slot=this.activeSlot()){const value=JSON.parse(readFileSync(this.dbPath(slot),'utf8'));this.validate(value);return value;}
 validate(value){if(!value||value.schemaVersion!==PHASE3.stateSchema||!Number.isSafeInteger(value.sequence))throw new Error('gateway_state_incompatible');}
 transaction(slot,mutate){const before=this.read(slot),draft=structuredClone(before);const result=mutate(draft);draft.sequence=before.sequence+1;this.validate(draft);atomicWriteJson(this.dbPath(slot),draft);return{state:draft,result};}
 prepareInactive({from=this.activeSlot(),releaseIdentity=null}={}){const to=from==='blue'?'green':'blue',source=this.read(from),copy=structuredClone(source);copy.migration={fromSchema:source.schemaVersion,toSchema:PHASE3.stateSchema,sourceSlot:from,destinationSlot:to,preparedAt:new Date(this.now()).toISOString()};copy.releaseIdentity=releaseIdentity;copy.sequence++;atomicWriteJson(this.dbPath(to),copy);return{from,to,sequence:copy.sequence};}
 activate(slot){const old=this.activeSlot();if(old===slot)return{active:slot,previous:existsSync(join(this.root,'previous'))?readlinkSync(join(this.root,'previous')).split('/').at(-1):null};const next=join(this.root,`active.${randomUUID()}`);symlinkSync(`slots/${slot}`,next);renameSync(join(this.root,'active'),join(this.root,'previous.tmp'));renameSync(next,join(this.root,'active'));if(existsSync(join(this.root,'previous')))unlinkSync(join(this.root,'previous'));renameSync(join(this.root,'previous.tmp'),join(this.root,'previous'));fsyncPath(this.root);return{active:slot,previous:old};}
 mergeSecurityTruth(fromSlot,toSlot){const source=this.read(fromSlot);this.transaction(toSlot,d=>{for(const[id,f]of Object.entries(source.refreshFamilies)){const current=d.refreshFamilies[id];if(!current||Number(f.generation)>Number(current.generation)||f.revoked)d.refreshFamilies[id]=structuredClone(f);}Object.assign(d.revocations.tokenIds,source.revocations.tokenIds);Object.assign(d.revocations.families,source.revocations.families);Object.assign(d.revocations.clients,source.revocations.clients);const consumed=new Set(d.replayEvents.map(e=>e.tokenHash));for(const e of source.replayEvents)if(!consumed.has(e.tokenHash))d.replayEvents.push(e);for(const[h,c]of Object.entries(source.authorizationCodes))if(c.consumed||c.expiresAt<=this.now())d.authorizationCodes[h]=structuredClone(c);});}
 snapshot(slot=this.activeSlot(),destination=join(this.root,'snapshots',`${slot}-${this.now()}`)){mkdirSync(destination,{recursive:false,mode:0o700});const state=this.read(slot),statePath=join(destination,'state.json');atomicWriteJson(statePath,state);const manifest={schemaVersion:PHASE3.stateSchema,slot,createdAt:new Date(this.now()).toISOString(),files:{'state.json':sha256(readFileSync(statePath))},keyReferences:['oauth-signing-key','refresh-hash-key','gateway-request-key'],containsPrivateKeys:false};atomicWriteJson(join(destination,'manifest.json'),manifest);return{destination,manifest};}
 restore(snapshot,destinationSlot){const manifest=JSON.parse(readFileSync(join(snapshot,'manifest.json'),'utf8'));if(manifest.schemaVersion!==PHASE3.stateSchema||manifest.containsPrivateKeys)throw new Error('gateway_state_incompatible');const bytes=readFileSync(join(snapshot,'state.json'));if(sha256(bytes)!==manifest.files['state.json'])throw new Error('gateway_state_corrupt');const state=JSON.parse(bytes);this.validate(state);atomicWriteJson(this.dbPath(destinationSlot),state);return{slot:destinationSlot,sequence:state.sequence};}

 acquireWriter(slot=this.activeSlot()){const lock=join(this.slotPath(slot),'writer.lock');let fd;try{fd=openSync(lock,'wx',0o600);writeFileSync(fd,JSON.stringify({pid:process.pid,slot,startedAt:new Date(this.now()).toISOString()}));fsyncSync(fd);}catch(error){if(error.code==='EEXIST')throw new Error('gateway_dual_writer');throw error;}this.writer={slot,lock,fd};return()=>this.releaseWriter();}
 releaseWriter(){if(!this.writer)return;try{closeSync(this.writer.fd);}finally{try{unlinkSync(this.writer.lock);}catch{}this.writer=null;}}
 issueRefresh(slot,binding){const raw=randomToken(48),hash=tokenHash(this.hashSecret,raw),familyId=randomUUID(),now=this.now();this.transaction(slot,d=>{d.refreshFamilies[familyId]={familyId,currentHash:hash,consumedHashes:[],generation:0,clientId:binding.clientId,subject:binding.subject,githubId:binding.githubId,resource:binding.resource,scope:[...binding.scope],createdAt:now,lastRotation:now,absoluteExpiry:binding.absoluteExpiry,idleExpiry:binding.idleExpiry,revoked:false,slot};});return{raw,familyId,generation:0};}
 rotateRefresh(slot,raw,binding){const hash=tokenHash(this.hashSecret,raw),before=this.read(slot),draft=structuredClone(before);const family=Object.values(draft.refreshFamilies).find(f=>f.currentHash===hash||f.consumedHashes.includes(hash));if(!family)throw new Error('oauth_invalid_grant');if(family.consumedHashes.includes(hash)){family.revoked=true;draft.revocations.families[family.familyId]={at:this.now(),reason:'refresh_replay'};draft.replayEvents.push({at:this.now(),familyId:family.familyId,tokenHash:hash});draft.sequence=before.sequence+1;atomicWriteJson(this.dbPath(slot),draft);throw new Error('token_replay');}if(family.revoked||draft.revocations.families[family.familyId])throw new Error('refresh_family_revoked');if(family.clientId!==binding.clientId||family.resource!==binding.resource)throw new Error('oauth_invalid_grant');const now=this.now();if(now>=family.absoluteExpiry||(family.idleExpiry&&now-family.lastRotation>family.idleExpiry)){family.revoked=true;draft.sequence=before.sequence+1;atomicWriteJson(this.dbPath(slot),draft);throw new Error('oauth_invalid_grant');}const next=randomToken(48),nextHash=tokenHash(this.hashSecret,next);family.consumedHashes.push(hash);family.currentHash=nextHash;family.generation++;family.lastRotation=now;draft.sequence=before.sequence+1;atomicWriteJson(this.dbPath(slot),draft);return{raw:next,familyId:family.familyId,generation:family.generation};}
}
