import http from 'node:http';
import {authorizationServerMetadata,protectedResourceMetadata,bearerChallenge} from './oauth.mjs';
import {mcpDispatch} from './mcp.mjs';
const json=(res,status,body,headers={})=>{const data=Buffer.from(JSON.stringify(body));res.writeHead(status,{'content-type':'application/json','content-length':data.length,'cache-control':'no-store',...headers});res.end(data);};
const body=async(req,limit)=>{let n=0,chunks=[];for await(const c of req){n+=c.length;if(n>limit)throw new Error('body_too_large');chunks.push(c);}if(!chunks.length)return{};const raw=Buffer.concat(chunks).toString('utf8'),type=String(req.headers['content-type']??'').split(';')[0];if(type==='application/x-www-form-urlencoded')return Object.fromEntries(new URLSearchParams(raw));if(type==='application/json')return JSON.parse(raw);throw new Error('unsupported_content_type');};
export function createGatewayServer({config,authority,gatewayClient,githubOAuth=null}){return http.createServer(async(req,res)=>{try{if(new URL(`http://${req.headers.host}`).hostname!==new URL(config.authorizationOrigin).hostname&&new URL(`http://${req.headers.host}`).hostname!==new URL(config.protectedResource).hostname)return json(res,400,{error:'invalid_host'});const u=new URL(req.url,config.authorizationOrigin);if(req.method==='GET'&&u.pathname==='/.well-known/oauth-authorization-server')return json(res,200,authorizationServerMetadata());if(req.method==='GET'&&u.pathname==='/.well-known/oauth-protected-resource')return json(res,200,protectedResourceMetadata(config.protectedResource));if(req.method==='GET'&&u.pathname==='/oauth/jwks.json')return json(res,200,authority.jwks());if(req.method==='POST'&&u.pathname==='/oauth/register')return json(res,201,authority.register(await body(req,config.requestBodyLimit??1048576)));
if(req.method==='GET'&&u.pathname==='/oauth/authorize'){const begun=authority.beginAuthorization(Object.fromEntries(u.searchParams));if(!githubOAuth)return json(res,503,{error:'github_oauth_failed'});const login=githubOAuth.begin(begun.transactionId);authority.state.transaction(authority.slot,d=>{d.githubLogins[login.stateHash]={...login,expiresAt:authority.now()+authority.stateTtl,used:false};});res.writeHead(302,{location:`${config.authorizationOrigin}/oauth/github?state=${encodeURIComponent(login.state)}`,'cache-control':'no-store'});return res.end();}
if(req.method==='GET'&&u.pathname==='/oauth/github'){if(!githubOAuth)return json(res,503,{error:'github_oauth_failed'});const h=(await import('node:crypto')).createHash('sha256').update(String(u.searchParams.get('state'))).digest('hex'),record=authority.state.read(authority.slot).githubLogins[h];if(!record||record.used||record.expiresAt<=authority.now())return json(res,400,{error:'github_oauth_failed'});res.writeHead(302,{location:record.authorizeUrl,'cache-control':'no-store'});return res.end();}
if(req.method==='GET'&&u.pathname==='/oauth/github/callback'){if(!githubOAuth)return json(res,503,{error:'github_oauth_failed'});const crypto=await import('node:crypto'),state=String(u.searchParams.get('state')??''),h=crypto.createHash('sha256').update(state).digest('hex'),record=authority.state.read(authority.slot).githubLogins[h];const user=await githubOAuth.callback({code:String(u.searchParams.get('code')??''),state,record});const code=authority.completeGithubIdentity(record.transactionId,user);authority.state.transaction(authority.slot,d=>{d.githubLogins[h].used=true;});const ar=authority.state.read(authority.slot).authorizationRequests[record.transactionId],client=authority.state.read(authority.slot).clients[ar.clientId],location=new URL(ar.redirectUri);location.searchParams.set('code',code);location.searchParams.set('state',ar.state);res.writeHead(302,{location:location.href,'cache-control':'no-store'});return res.end();}if(req.method==='POST'&&u.pathname==='/oauth/token'){const i=await body(req,config.requestBodyLimit??1048576);return json(res,200,i.grant_type==='refresh_token'?authority.refresh(i):authority.exchangeCode(i));}if(req.method==='POST'&&u.pathname==='/oauth/revoke'){authority.revoke(await body(req,config.requestBodyLimit??1048576));return json(res,200,{});}if(u.pathname==='/mcp'){const auth=req.headers.authorization;if(typeof auth!=='string'||!auth.startsWith('Bearer '))return json(res,401,{error:'mcp_unauthorized'},{'www-authenticate':bearerChallenge(config.protectedResource)});const token=auth.slice(7);let message;try{message=await body(req,config.requestBodyLimit??1048576);}catch{return json(res,400,{error:'mcp_protocol_error'});}try{return json(res,200,await mcpDispatch(message,{authority,token,gatewayClient}));}catch(e){const forbidden=e.message==='mcp_forbidden';return json(res,forbidden?403:401,{error:forbidden?'mcp_forbidden':'mcp_unauthorized'},{...(forbidden?{}:{'www-authenticate':bearerChallenge(config.protectedResource)})});}}return json(res,404,{error:'not_found'});}catch(e){return json(res,400,{error:e.message});}});}
export async function listenLoopback(server,host,port){if(!['127.0.0.1','::1'].includes(host))throw new Error('public_mcp_binding_forbidden');await new Promise((resolve,reject)=>server.once('error',reject).listen(port,host,resolve));return server.address();}
