import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {execFileSync} from 'node:child_process';
const repo=process.cwd();
const base=process.env.SEZ_01A_PACKAGE||'/root/se-z-phase1-work/final-b9b6cadb5c2b/package/release/se-z-0.1A-b9b6cadb5c2b.tar.gz';
const expectedBase='75bad6893807f549c999d81f7d3c8b396faac88731ef48969ec43767dd29e189';
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
if(!fs.existsSync(base)||sha(fs.readFileSync(base))!==expectedBase)throw new Error('accepted 0.1A package unavailable or digest mismatch');
const commit=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim();
const tree=execFileSync('git',['rev-parse','HEAD^{tree}'],{encoding:'utf8'}).trim();
const work=fs.mkdtempSync('/var/tmp/se-z-01b-package-');
const root=path.join(work,'root');fs.mkdirSync(root);
execFileSync('tar',['-xzf',base,'-C',root]);
const cp=(src,dst)=>{fs.mkdirSync(path.dirname(dst),{recursive:true});fs.cpSync(src,dst,{recursive:true});};
cp('src/phase3',path.join(root,'payload/libexec/phase3'));
cp('src/kernel',path.join(root,'payload/libexec/kernel'));
cp('src/bin',path.join(root,'payload/bin'));
cp('packaging/phase2/install/verify-install.mjs',path.join(root,'payload/libexec/install/verify-install.mjs'));
for(const f of fs.readdirSync('packaging/phase3/systemd'))cp(path.join('packaging/phase3/systemd',f),path.join(root,'payload/share/systemd',f));
cp('packaging/phase3/tmpfiles/se-z-gateway.conf',path.join(root,'payload/share/tmpfiles/se-z-gateway.conf'));
cp('packaging/phase3/install/openai-tunnel-launcher',path.join(root,'payload/libexec/phase3/openai-tunnel-launcher'));
for(const f of fs.readdirSync('contracts').filter(x=>x.includes('0.1b')))cp(path.join('contracts',f),path.join(root,'payload/contracts',f));
fs.renameSync(path.join(root,'install/install-package'),path.join(root,'install/install-package.core'));
cp('packaging/phase3/install/install-package-overlay',path.join(root,'install/install-package'));
fs.chmodSync(path.join(root,'install/install-package'),0o755);fs.chmodSync(path.join(root,'install/install-package.core'),0o755);
const manifest=JSON.parse(fs.readFileSync(path.join(root,'manifest.json'),'utf8'));
const ops=JSON.parse(fs.readFileSync('contracts/operations-0.1b.json','utf8'));
const kernelCatalog=JSON.parse(execFileSync(process.execPath,['--input-type=module','-e',"import('./src/kernel/definitions.mjs').then(m=>console.log(JSON.stringify({digest:m.CATALOG_DIGEST,count:m.ACTIVE_OPERATION_NAMES.length})))"],{encoding:'utf8'}));
Object.assign(manifest,{releaseMilestone:'0.1B',sourceCommit:commit,sourceTree:tree,sourceDateEpoch:1785800000,stateSchemaVersion:'0.1A.1',gatewayStateSchemaVersion:'0.1B.1',kernelAncestry:'b9b6cadb5c2b87d066526348c86cb6bba88f9832',candidate:true,productionActive:false,standaloneComplete:false,tunnelClientIdentityRequirement:'current official OpenAI Secure MCP Tunnel client, verified at runtime',phase3CatalogDigest:kernelCatalog.digest,supervisorCatalogDigest:kernelCatalog.digest,operationCount:kernelCatalog.count});
manifest.operationDefinitionSha256=sha(fs.readFileSync('contracts/operations-0.1b.json'));
manifest.oauthMetadataSha256=sha(Buffer.from(JSON.stringify({issuer:'https://auth.se-z.stealtheye.io',scopes:['sez.root','offline_access']})));
manifest.releaseId=sha(Buffer.from(JSON.stringify({product:'se-z',milestone:'0.1B',commit,tree,catalogDigest:kernelCatalog.digest})));
const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)]);
const tracked=walk(path.join(root,'payload')).concat([path.join(root,'install/install-package'),path.join(root,'install/install-package.core')]).sort();
manifest.files=tracked.map(f=>({path:path.relative(root,f),bytes:fs.statSync(f).size,mode:(fs.statSync(f).mode&0o777).toString(8).padStart(4,'0'),sha256:sha(fs.readFileSync(f))}));
fs.writeFileSync(path.join(root,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');
const checks=walk(root).filter(f=>path.basename(f)!=='SHA256SUMS').sort();
fs.writeFileSync(path.join(root,'SHA256SUMS'),checks.map(f=>`${sha(fs.readFileSync(f))}  ${path.relative(root,f)}`).join('\n')+'\n');
const outdir=path.join(repo,'dist');fs.mkdirSync(outdir,{recursive:true});
const archive=path.join(outdir,`se-z-0.1B-${commit.slice(0,12)}.tar.gz`);
execFileSync('tar',['--sort=name','--mtime=@1785800000','--owner=0','--group=0','--numeric-owner','-czf',archive,'-C',root,'.'],{env:{...process.env,GZIP:'-n'}});
const result={archive,size:fs.statSync(archive).size,sha256:sha(fs.readFileSync(archive)),releaseId:manifest.releaseId,sourceCommit:commit,sourceTree:tree,catalogDigest:kernelCatalog.digest,base01aSha256:expectedBase};
fs.rmSync(work,{recursive:true,force:true});
console.log(JSON.stringify(result));
