import { createHash } from 'node:crypto';

export const CORE_OPERATIONS = Object.freeze([
  'sez.describe',
  'sez.health',
  'sez.version',
  'sez.doctor',
  'sez.request.resume',
  'sez.exec',
  'sez.shell',
  'sez.job.get',
  'sez.job.list',
  'sez.job.wait',
  'sez.job.cancel',
  'sez.job.stream.read',
  'sez.file.stat',
  'sez.file.read',
  'sez.file.write',
  'sez.file.replace',
  'sez.file.remove',
  'sez.file.list',
  'sez.pty.create',
  'sez.pty.input',
  'sez.pty.resize',
  'sez.pty.read',
  'sez.pty.close',
  'sez.artifact.create',
  'sez.artifact.begin',
  'sez.artifact.upload',
  'sez.artifact.finalize',
  'sez.artifact.download',
  'sez.github.app.verify',
  'sez.github.api',
  'sez.github.git',
  'sez.github.reconcile',
  'sez.machine.create',
  'sez.machine.start',
  'sez.machine.stop',
  'sez.machine.status',
  'sez.machine.delete',
  'sez.skill.deploy',
  'sez.skill.status',
  'sez.skill.rollback',
  'sez.release.status',
  'sez.release.build',
  'sez.release.stage',
  'sez.release.verify',
  'sez.release.activate',
  'sez.release.rollback',
  'sez.release.repair',
  'sez.recovery.status',
  'sez.recovery.upgrade',
  'sez.recovery.rollback',
  'sez.backup.create',
  'sez.backup.restore'
]);

export function catalogDigest(operations = CORE_OPERATIONS) {
  return createHash('sha256').update(JSON.stringify([...operations].sort())).digest('hex');
}
