import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,writeFileSync,symlinkSync,mkdirSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {generateKeyPairSync,sign} from 'node:crypto';
import {GatewayState} from '../../src/phase3/atomic-state.mjs';import {OAuthAuthority,generateOAuthKey,pkceChallenge,authorizationServerMetadata,protectedResourceMetadata,bearerChallenge,markLegacyChatGptPublicClients} from '../../src/phase3/oauth.mjs';import {TOOL,validateCall,mcpDispatch} from '../../src/phase3/mcp.mjs';import {PHASE3,CALL_SEZ_SCHEMA} from '../../src/phase3/constants.mjs';import {GatewaySez1Client,digest} from '../../src/phase3/sez1-gateway.mjs';import {AcceptanceFencer,RecoveryUnavailable,ReleaseController} from '../../src/phase3/release-control.mjs';import {validateGatewayConfig} from '../../src/phase3/config.mjs';
function fixture(nowRef={value:1800000000000}){const root=mkdtempSync(join(tmpdir(),'sez-p3-')),state=new GatewayState(root,{hashSecret:Buffer.alloc(32,7),now:()=>nowRef.value}),keys=generateOAuthKey(),resource='https://candidate.example.invalid/mcp',auth=new OAuthAuthority({state,slot:'blue',resource,privateKey:keys.privateKey,now:()=>nowRef.value});return{root,state,keys,auth,resource,nowRef};}
function flow(f){const verifier='A'.repeat(43),reg=f.auth.register({redirect_uris:['https://chatgpt.com/aip/callback'],grant_types:['authorization_code','refresh_token'],response_types:['code'],token_endpoint_auth_method:'none',client_name:'candidate'}),begin=f.auth.beginAuthorization({response_type:'code',client_id:reg.client_id,redirect_uri:reg.redirect_uris[0],scope:'sez.root offline_access',state:'state-12345678',code_challenge:pkceChallenge(verifier),code_challenge_method:'S256',resource:f.resource}),code=f.auth.completeGithubIdentity(begin.transactionId,{id:247854506}),token=f.auth.exchangeCode({code,client_id:reg.client_id,redirect_uri:reg.redirect_uris[0],code_verifier:verifier,resource:f.resource});return{reg,begin,code,token,verifier};}
test('metadata and exact one tool',()=>{const f=fixture();assert.equal(authorizationServerMetadata().issuer,PHASE3.issuer);assert.deepEqual(protectedResourceMetadata(f.resource),{resource:f.resource,authorization_servers:[PHASE3.issuer],bearer_methods_supported:['header'],scopes_supported:['sez.root','offline_access']});assert.equal(bearerChallenge(f.resource),`Bearer resource_metadata="${f.resource}/.well-known/oauth-protected-resource", scope="sez.root offline_access"`);assert.equal(TOOL.name,'call_sez');assert.deepEqual(TOOL.inputSchema,CALL_SEZ_SCHEMA);assert.equal(Object.hasOwn(TOOL.inputSchema.properties.operation,'enum'),false);});
test('registration persistence and strict redirect',()=>{const f=fixture(),r=f.auth.register({redirect_uris:['https://chatgpt.com/aip/callback']});assert.ok(f.state.read('blue').clients[r.client_id]);assert.throws(()=>f.auth.register({redirect_uris:['https://evil.invalid/cb#x']}),/redirect_uri/);assert.ok(new GatewayState(f.root,{hashSecret:Buffer.alloc(32,7)}).read('blue').clients[r.client_id]);});
test('confidential DCR client allows omitted PKCE only with token endpoint secret',()=>{const f=fixture(),base={redirect_uris:['https://chatgpt.com/aip/callback'],grant_types:['authorization_code','refresh_token'],response_types:['code'],client_name:'ChatGPT'},publicClient=f.auth.register({...base,token_endpoint_auth_method:'none'}),confidential=f.auth.register({...base,token_endpoint_auth_method:'client_secret_post'});assert.notEqual(confidential.client_id,publicClient.client_id);assert.equal(confidential.token_endpoint_auth_method,'client_secret_post');assert.ok(confidential.client_secret.length>=43);assert.throws(()=>f.auth.beginAuthorization({response_type:'code',client_id:publicClient.client_id,redirect_uri:publicClient.redirect_uris[0],scope:'sez.root offline_access',state:'state-public-123',resource:f.resource}),/pkce_required/);const begin=f.auth.beginAuthorization({response_type:'code',client_id:confidential.client_id,redirect_uri:confidential.redirect_uris[0],scope:'sez.root offline_access',state:'state-confidential-123',resource:f.resource}),code=f.auth.completeGithubIdentity(begin.transactionId,{id:247854506});assert.throws(()=>f.auth.exchangeCode({code,client_id:confidential.client_id,redirect_uri:confidential.redirect_uris[0],resource:f.resource}),/oauth_invalid_client/);assert.throws(()=>f.auth.exchangeCode({code,client_id:confidential.client_id,client_secret:'wrong-secret',redirect_uri:confidential.redirect_uris[0],resource:f.resource}),/oauth_invalid_client/);const token=f.auth.exchangeCode({code,client_id:confidential.client_id,client_secret:confidential.client_secret,redirect_uri:confidential.redirect_uris[0],resource:f.resource});assert.equal(f.auth.verifyAccess(token.access_token).aud,f.resource);});
test('PKCE, one-time code, exact resource, numeric owner',()=>{const f=fixture(),x=flow(f);assert.equal(f.auth.verifyAccess(x.token.access_token).aud,f.resource);assert.throws(()=>f.auth.exchangeCode({code:x.code,client_id:x.reg.client_id,redirect_uri:x.reg.redirect_uris[0],code_verifier:x.verifier,resource:f.resource}),/oauth_invalid_grant/);const g=fixture(),v='B'.repeat(43),r=g.auth.register({redirect_uris:['https://chatgpt.com/aip/callback']}),a=g.auth.beginAuthorization({response_type:'code',client_id:r.client_id,redirect_uri:r.redirect_uris[0],scope:'sez.root',state:'state-12345678',code_challenge:pkceChallenge(v),code_challenge_method:'S256',resource:g.resource});assert.throws(()=>g.auth.completeGithubIdentity(a.transactionId,{id:1,login:'StealthEyeLLC'}),/github_identity_mismatch/);assert.throws(()=>g.auth.beginAuthorization({...a,client_id:r.client_id,redirect_uri:r.redirect_uris[0],response_type:'code',scope:'sez.root',state:'state-12345678',code_challenge:pkceChallenge(v),code_challenge_method:'plain',resource:g.resource}),/pkce_required/);});
test('confidential DCR allows omitted PKCE only with a token endpoint secret',()=>{const f=fixture(),base={redirect_uris:['https://client.example/callback'],grant_types:['authorization_code','refresh_token'],response_types:['code'],client_name:'Generic client'},publicClient=f.auth.register({...base,token_endpoint_auth_method:'none'}),confidential=f.auth.register({...base,token_endpoint_auth_method:'client_secret_post'}),confidentialRetry=f.auth.register({...base,token_endpoint_auth_method:'client_secret_post'});assert.notEqual(publicClient.client_id,confidential.client_id);assert.notEqual(confidential.client_id,confidentialRetry.client_id);assert.ok(confidential.client_secret);assert.ok(confidentialRetry.client_secret);assert.throws(()=>f.auth.beginAuthorization({response_type:'code',client_id:publicClient.client_id,redirect_uri:publicClient.redirect_uris[0],scope:'sez.root offline_access',state:'state-public-1234',resource:f.resource}),/pkce_required/);const begin=f.auth.beginAuthorization({response_type:'code',client_id:confidential.client_id,redirect_uri:confidential.redirect_uris[0],scope:'sez.root offline_access',state:'state-confidential-1234',resource:f.resource}),code=f.auth.completeGithubIdentity(begin.transactionId,{id:247854506});assert.throws(()=>f.auth.exchangeCode({code,client_id:confidential.client_id,redirect_uri:confidential.redirect_uris[0],resource:f.resource}),/oauth_invalid_client/);const token=f.auth.exchangeCode({code,client_id:confidential.client_id,client_secret:confidential.client_secret,redirect_uri:confidential.redirect_uris[0],resource:f.resource});assert.equal(f.auth.verifyAccess(token.access_token).client_id,confidential.client_id);assert.ok(token.refresh_token);});
test('refresh rotates once, replay revokes family, revocation persists',()=>{const f=fixture(),x=flow(f),n=f.auth.refresh({refresh_token:x.token.refresh_token,client_id:x.reg.client_id,resource:f.resource});assert.notEqual(n.refresh_token,x.token.refresh_token);assert.throws(()=>f.auth.refresh({refresh_token:x.token.refresh_token,client_id:x.reg.client_id,resource:f.resource}),/token_replay/);assert.equal(Object.values(f.state.read('blue').refreshFamilies)[0].revoked,true);assert.throws(()=>f.auth.refresh({refresh_token:n.refresh_token,client_id:x.reg.client_id,resource:f.resource}),/refresh_family_revoked/);const g=fixture(),y=flow(g);g.auth.revoke({token:y.token.access_token,client_id:y.reg.client_id});assert.throws(()=>g.auth.verifyAccess(y.token.access_token),/token_revoked/);});
test('slot migration and snapshot reject corruption',()=>{const f=fixture(),x=flow(f);f.state.prepareInactive({releaseIdentity:'green'});const ga=new OAuthAuthority({state:f.state,slot:'green',resource:f.resource,privateKey:f.keys.privateKey,now:()=>f.nowRef.value});ga.refresh({refresh_token:x.token.refresh_token,client_id:x.reg.client_id,resource:f.resource});f.state.mergeSecurityTruth('green','blue');assert.equal(Object.values(f.state.read('blue').refreshFamilies)[0].generation,1);const snap=f.state.snapshot('blue');writeFileSync(join(snap.destination,'state.json'),'{}\n');assert.throws(()=>f.state.restore(snap.destination,'green'),/gateway_state_corrupt/);});
test('MCP derives authority and keeps schema frozen',async()=>{const f=fixture(),x=flow(f),seen=[],client={call:async v=>(seen.push(v),{requestId:'r',operation:v.operation,state:'completed',terminal:true,catalogDigest:'a'.repeat(64),receiptVerified:true})};const list=await mcpDispatch({jsonrpc:'2.0',id:1,method:'tools/list'},{authority:f.auth,token:x.token.access_token,gatewayClient:client});assert.deepEqual(list.result.tools.map(t=>t.name),['call_sez']);await mcpDispatch({jsonrpc:'2.0',id:2,method:'tools/call',params:{name:'call_sez',arguments:{operation:'sez.describe',payload:{},idempotencyKey:'abcdefgh'}}},{authority:f.auth,token:x.token.access_token,gatewayClient:client});assert.equal(seen[0].transport.subject,'stealtheye-owner');assert.throws(()=>validateCall({operation:'sez.exec',payload:{},idempotencyKey:'abcdefgh',subject:'root'}),/invalid_sez_call/);});
test('signed SEZ1 and receipt verification',async()=>{const g=generateKeyPairSync('ed25519'),r=generateKeyPairSync('ed25519');let captured;const c=new GatewaySez1Client({gatewayId:'g',gatewayKeyId:'gk',privateKey:g.privateKey,receiptKeys:[{keyId:'rk',key:r.publicKey}],handshake:async()=>({authorityGeneration:9}),sender:async req=>{captured=req;const result={ok:true},body={requestId:req.requestId,operation:req.operation,authorityGeneration:req.authorityGeneration,catalogDigest:'c'.repeat(64),resultDigest:digest(result),keyId:'rk'};return{requestId:req.requestId,operation:req.operation,authorityGeneration:req.authorityGeneration,catalogDigest:'c'.repeat(64),result,receipt:{...body,signature:sign(null,Buffer.from(digest(body),'hex'),r.privateKey).toString('base64')}};}});assert.equal((await c.call({operation:'sez.describe',payload:{},idempotencyKey:'abcdefgh'})).receiptVerified,true);assert.equal(captured.peerClass,'gateway-signed');assert.equal(captured.subject,'stealtheye-owner');});
test('strict config and production recovery fail closed',async()=>{const cfg={issuer:PHASE3.issuer,protectedResource:'https://candidate.invalid/mcp',authorizationOrigin:PHASE3.issuer,mcpHost:'127.0.0.1',mcpPort:2096,stateRoot:PHASE3.stateRoot,activeSlot:'blue',gatewayStateSchema:PHASE3.stateSchema,gatewayId:'g',gatewayKeyId:'gk',gatewaySigningCredential:'cred:g',receiptVerificationKeys:['rk'],oauthSigningCredential:'cred:o',oauthAcceptedKeys:['ok'],refreshHashCredential:'cred:r',githubOAuthClientId:'test-client-id',githubOAuthClientIdCredential:'cred:cid',githubOAuthClientSecretCredential:'cred:cs',githubCallbackUri:`${PHASE3.issuer}/oauth/github/callback`,ownerGithubId:PHASE3.ownerGithubId,supervisorGatewaySocket:PHASE3.gatewaySocket,releaseIdentity:'0.1B'};assert.equal(validateGatewayConfig(cfg).mcpHost,'127.0.0.1');assert.throws(()=>validateGatewayConfig({...cfg,mcpHost:'0.0.0.0'}),/loopback/);const f=fixture(),rc=new ReleaseController({root:join(f.root,'release'),fencingAuthority:new RecoveryUnavailable(),gatewayState:f.state});rc.build({deploymentId:'d',sourceCommit:'a'.repeat(40),sourceTree:'b'.repeat(40),packageDigest:'c'.repeat(64)});rc.stage('d');rc.verify('d',{manifest:true});await assert.rejects(()=>rc.activate('d'),/release_recovery_unavailable/);assert.equal(rc.status('d').state,'verified');});
test('acceptance fencer removes writers and activates',async()=>{const f=fixture(),root=join(f.root,'fencer');mkdirSync(root,{recursive:true});symlinkSync('blue-release',join(root,'active'));let writers=[1,2];const pc={block(){},enumerate(){return[...writers]},async stopAll(){writers=[]}},rc=new ReleaseController({root:join(f.root,'release'),fencingAuthority:new AcceptanceFencer({root,processController:pc}),gatewayState:f.state});rc.build({deploymentId:'ok',sourceCommit:'a'.repeat(40),sourceTree:'b'.repeat(40),packageDigest:'c'.repeat(64)});rc.stage('ok');rc.verify('ok',{manifest:true,gateway:true});assert.equal((await rc.activate('ok',{accept:async()=>true})).state,'accepted');assert.deepEqual(writers,[]);});
test('slot writer lease rejects a second writable gateway',()=>{const f=fixture();const release=f.state.acquireWriter('blue');const second=new GatewayState(f.root,{hashSecret:Buffer.alloc(32,7)});assert.throws(()=>second.acquireWriter('blue'),/gateway_dual_writer/);release();const release2=second.acquireWriter('blue');release2();});
test('OAuth signing key overlap accepts old access token and rejects unknown key',()=>{const f=fixture(),x=flow(f),next=generateOAuthKey(),rotated=new OAuthAuthority({state:f.state,slot:'blue',resource:f.resource,privateKey:next.privateKey,keyId:'oauth-signing-v2',acceptedPublicKeys:[{keyId:'oauth-signing-v1',key:f.keys.publicKey}],now:()=>f.nowRef.value});assert.equal(rotated.verifyAccess(x.token.access_token).sub,'stealtheye-owner');const other=fixture();assert.throws(()=>other.auth.verifyAccess(x.token.access_token),/token_invalid/);});
test('concurrent refresh issues only one successor',async()=>{const f=fixture(),x=flow(f);const attempts=await Promise.allSettled([Promise.resolve().then(()=>f.auth.refresh({refresh_token:x.token.refresh_token,client_id:x.reg.client_id,resource:f.resource})),Promise.resolve().then(()=>f.auth.refresh({refresh_token:x.token.refresh_token,client_id:x.reg.client_id,resource:f.resource}))]);assert.equal(attempts.filter(x=>x.status==='fulfilled').length,1);assert.equal(attempts.filter(x=>x.status==='rejected').length,1);});

test('ChatGPT tunnel DCR is confidential when the beta client omits PKCE, while ordinary public clients still require PKCE',()=>{
  const f=fixture(),base={redirect_uris:['https://chatgpt.com/connector/oauth/test-callback'],grant_types:['authorization_code','refresh_token'],response_types:['code'],token_endpoint_auth_method:'none',client_name:'ChatGPT'};
  const confidential=f.auth.register(base);
  assert.equal(confidential.token_endpoint_auth_method,'client_secret_post');
  assert.ok(confidential.client_secret?.length>=43);
  const begin=f.auth.beginAuthorization({response_type:'code',client_id:confidential.client_id,redirect_uri:confidential.redirect_uris[0],scope:'sez.root offline_access',state:'chatgpt-state-1234',resource:f.resource});
  const code=f.auth.completeGithubIdentity(begin.transactionId,{id:247854506});
  assert.throws(()=>f.auth.exchangeCode({code,client_id:confidential.client_id,redirect_uri:confidential.redirect_uris[0],resource:f.resource}),/oauth_invalid_client/);
  const token=f.auth.exchangeCode({code,client_id:confidential.client_id,client_secret:confidential.client_secret,redirect_uri:confidential.redirect_uris[0],resource:f.resource});
  assert.equal(f.auth.verifyAccess(token.access_token).client_id,confidential.client_id);
  const publicClient=f.auth.register({...base,client_name:'Other client',redirect_uris:['https://client.example/callback']});
  assert.equal(publicClient.token_endpoint_auth_method,'none');
  assert.equal(publicClient.client_secret,undefined);
  assert.throws(()=>f.auth.beginAuthorization({response_type:'code',client_id:publicClient.client_id,redirect_uri:publicClient.redirect_uris[0],scope:'sez.root',state:'public-state-1234',resource:f.resource}),/pkce_required/);
});

test('persisted pre-fix ChatGPT public clients are narrowly migrated and remain bound to the exact connector callback',()=>{
  const f=fixture(),callback='https://chatgpt.com/connector/oauth/legacy-callback',base={redirect_uris:[callback],grant_types:['authorization_code','refresh_token'],response_types:['code'],token_endpoint_auth_method:'none',client_name:'Other client'};
  const legacy=f.auth.register(base);
  f.state.transaction('blue',d=>{const c=d.clients[legacy.client_id];c.client_name='ChatGPT';c.publicMetadata.client_name='ChatGPT';});
  assert.throws(()=>f.auth.beginAuthorization({response_type:'code',client_id:legacy.client_id,redirect_uri:callback,scope:'sez.root offline_access',state:'legacy-before-migration',resource:f.resource}),/pkce_required/);
  assert.equal(markLegacyChatGptPublicClients(f.state,'blue',f.nowRef.value),1);
  assert.equal(markLegacyChatGptPublicClients(f.state,'blue',f.nowRef.value),0);
  const stored=f.state.read('blue').clients[legacy.client_id];
  assert.equal(stored.legacyChatGPTNoPkce,true);
  assert.equal(stored.legacyChatGPTNoPkceMarkedAt,f.nowRef.value);
  const begin=f.auth.beginAuthorization({response_type:'code',client_id:legacy.client_id,redirect_uri:callback,scope:'sez.root offline_access',state:'legacy-after-migration',resource:f.resource}),code=f.auth.completeGithubIdentity(begin.transactionId,{id:247854506}),token=f.auth.exchangeCode({code,client_id:legacy.client_id,redirect_uri:callback,resource:f.resource});
  assert.equal(f.auth.verifyAccess(token.access_token).client_id,legacy.client_id);
  assert.ok(token.refresh_token);
  const ordinary=f.auth.register({...base,client_name:'Other client',redirect_uris:['https://chatgpt.com/connector/oauth/ordinary-public']});
  assert.equal(markLegacyChatGptPublicClients(f.state,'blue',f.nowRef.value),0);
  assert.throws(()=>f.auth.beginAuthorization({response_type:'code',client_id:ordinary.client_id,redirect_uri:ordinary.redirect_uris[0],scope:'sez.root',state:'ordinary-public-state',resource:f.resource}),/pkce_required/);
  const wrongHost=f.auth.register({...base,client_name:'ChatGPT',redirect_uris:['https://client.example/callback'],token_endpoint_auth_method:'none'});
  assert.equal(wrongHost.token_endpoint_auth_method,'none');
  assert.equal(markLegacyChatGptPublicClients(f.state,'blue',f.nowRef.value),0);
  assert.throws(()=>f.auth.beginAuthorization({response_type:'code',client_id:wrongHost.client_id,redirect_uri:wrongHost.redirect_uris[0],scope:'sez.root',state:'wrong-host-state',resource:f.resource}),/pkce_required/);
});
