import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,mkdirSync,symlinkSync,readlinkSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {GatewayState} from '../../src/phase3/atomic-state.mjs';import {AcceptanceFencer,ReleaseController} from '../../src/phase3/release-control.mjs';
function fx(){const root=mkdtempSync(join(tmpdir(),'p3-release-')),state=new GatewayState(join(root,'gateway'),{hashSecret:Buffer.alloc(32,3)}),froot=join(root,'fencer');mkdirSync(froot);symlinkSync('blue-release',join(froot,'active'));let writers=['blue'];let blocked=false;const pc={block(){blocked=true},enumerate(){return [...writers]},async stopAll(){writers=[]},start(name){writers=[name]},get blocked(){return blocked}};const fencer=new AcceptanceFencer({root:froot,processController:pc}),controller=new ReleaseController({root:join(root,'release'),fencingAuthority:fencer,gatewayState:state});return{root,state,froot,pc,controller};}
function prep(f,id='d'){f.controller.build({deploymentId:id,sourceCommit:'a'.repeat(40),sourceTree:'b'.repeat(40),packageDigest:'c'.repeat(64)});f.controller.stage(id);f.controller.verify(id,{manifest:true,gateway:true,supervisor:true});}
test('scenario A successful blue to green',async()=>{const f=fx();prep(f);const out=await f.controller.activate('d',{accept:async()=>{f.pc.start('green');return true}});assert.equal(out.state,'accepted');assert.equal(f.state.activeSlot(),'green');assert.deepEqual(f.pc.enumerate(),['green']);});
test('scenarios B/C failed candidate start roll back',async()=>{for(const kind of ['gateway','supervisor']){const f=fx();prep(f,kind);const out=await f.controller.activate(kind,{accept:async()=>false});assert.equal(out.state,'rolled_back');assert.equal(f.state.activeSlot(),'blue');}});
test('scenario D tunnel remote acceptance failure rolls back',async()=>{const f=fx();prep(f,'tunnel');const out=await f.controller.activate('tunnel',{accept:async()=>false});assert.equal(out.state,'rolled_back');});
test('scenario E incompatible migration rejected before activation',()=>{const f=fx();prep(f,'migration');assert.throws(()=>f.controller.verify('migration',{manifest:true,migration:false}),/release_verify_failed/);});
test('scenario F response loss status returns actual accepted state',async()=>{const f=fx();prep(f,'loss');await assert.rejects(()=>f.controller.activate('loss',{accept:async()=>true,responseLoss:true}),/response_lost/);assert.equal(f.controller.status('loss').state,'accepted');});
test('scenario G interrupted rollback repaired from actual pointers',async()=>{const f=fx();prep(f,'repair');let first=true;const original=f.controller.fencer.rollback.bind(f.controller.fencer);f.controller.fencer.rollback=async()=>{if(first){first=false;throw new Error('interrupted')}return original()};await assert.rejects(()=>f.controller.activate('repair',{accept:async()=>false}),/interrupted/);assert.equal(f.controller.status('repair').state,'rolling_back');f.controller.fencer.rollback=original;const out=await f.controller.repair('repair');assert.equal(out.state,'repaired');assert.deepEqual(f.pc.enumerate(),[]);});
